config/routes.rb
Rails.application.routes.draw do
  get 'library_game/index'
  devise_for :users
  root to: 'pages#home'
  get '/games', to: 'games#index', as: :index
  get '/user/:id', to: 'user#show'
  resource :user, only: [] do
    resources :games, only: [:create, :destroy]
  end
  get '/user/:id/library', to: 'library#index', as: :library
  post '/user/:id/library', to: 'games#create', as: :create
  #delete 'user/:id/library', to: 'games#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :library_games
  has_many :libraries, through: :library_games
  has_many :users, through: :libraries
  serialize :data
  attr_accessor :game_id

  def fetch_data
    game = GiantBomb::Game.detail(game_id)
    self.data = Hash[game.instance_variables.map { |var| [var.to_s[1..-1], game.instance_variable_get(var)] } ]
  end

  def to_giant_bomb_game
    GiantBomb::Game.new(data)
  end
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  has_many :library_games
  has_many :games, through: :library_games
end

app/models/library_game.rb
class LibraryGame < ApplicationRecord
  belongs_to :library
  belongs_to :game
  has_one :user, through: :library
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :library
  has_many :games, through: :library

  def has_game?(game)
    games.where(id: game.id).exist?
  end

  def build_library
    return if library.present?
    self.library = Library.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
  @games = GiantBomb::Search.new().query(params[:query]).resources('game').limit(100).fetch
  end

  def show
  @game = GiantBomb::Game.detail(params[:id])
  end

  def create
    @library_game = Game.new
    @library_game.game_id = params[:game_id]
    @library_game.fetch_data
    @library_game.save!
    current_user.build_library
    current_user.library.games << @library_game
    flash[:notice] = "Added to library!"
    redirect_to library_path
  end

  def destroy
    current_user.games.find(params[:id]).destroy
    flash[:notice] = "Removed from library!"
    redirect_to library_path(current_user)
  end

private

  #def game_params
  #  params.require(:game).permit(:data)
  #end

  #def get_game_id
  #  params.require(:game)['id']
  #end

end

app/controllers/library_controller.rb
class LibraryController < ApplicationController

  def index
    @library_games = User.find(params[:id]).games
  end
end

app/controllers/library_game_controller.rb
class LibraryGameController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def games
    @game = GiantBomb::Game.detail(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="container">
  <div class="row">
    <div class="mt-3 mb-3">
      <%= form_tag index_path, method: :get do %>
      <%= text_field_tag [:query],
      params[:query],
      class: "form-control",
        id: "typed-text" %>
      </div>
      <div class="input-group-btn mt-3 mb-3">
        <%= submit_tag "Search", class: "btn goldbutton_search" %>
      </div>
      <% end %>
  </div>
</div>
<div class="cards">
  <% @games.each do |game| %>
  <div class="wrapper">
    <div class="product-img">
  <%= image_tag game['image']['medium_url'], class: "cover"%>
    </div>
  <div class="product-info">
      <div class="product-text">
    <h1><%= game['name'] %></h1>
    <% if game['platforms'] === nil %>
    <h2>Platform Unknown (<%= game['original_release_date'].to_s[0..3] %>)</h2>
    <% else %>
    <h2><%= game['platforms'][0]['name'] %> (<%= game['original_release_date'].to_s[0..3] %>)</h2>
    <% end %>
    <p><%= game['deck'] %></p>
    </div>

    <div class="product-price-btn">

       <%= link_to '<button type="button">Add to library</button>'.html_safe, create_path(current_user, game_id: game['id']), method: :post %>

      </div>
    </div>
  </div>

  <% end %>
  </div>

app/views/games/show.html.erb
<div class="cards">

  <div class="card">
  <%= image_tag @game.image['medium_url'], class: "cover"%>
  <div class="container">
    <h2><%= @game.name %></h2>
    <p><%= @game.deck %></p>
    <p><%= @game.id %></p>
    <% if @game.platforms === nil %>
    <p>Platform Unknown</p>
    <% else %>
    <p><%= @game.platforms[0]['name'] %></p>
    <% end %>
    <p><%= @game.original_release_date.to_s[0..3] %></p>
  </div>
</div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GAMEBAKO | Build Your Game Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/library/index.html.erb
<h1 class="title"><%= User.find(params[:id]).username %>'s Library</h1>
<div class="cards">
<% if @library_games.exists? %>
<% @library_games.each do |library_game| %>
<% game = library_game.to_giant_bomb_game %>
<div class="wrapper">
    <div class="product-img">
      <%= image_tag game.image['medium_url'], class: "cover"%>
    </div>
    <div class="product-info">
      <div class="product-text">
        <h1><%= game.name %></h1>
        <% if game.platforms === nil %>
    <h2>Platform Unknown (<%= game.original_release_date.to_s[0..3] %>)</h2>
    <% else %>
    <h2><%= game.platforms[0]['name'] %> (<%= game.original_release_date.to_s[0..3] %>)</h2>
    <% end %>
        <p><%= game.deck %> </p>
      </div>
      <div class="product-price-btn">
           <%= link_to '<button type="button">Remove from library</button>'.html_safe, user_game_path(library_game.id), method: :delete %>

      </div>
    </div>
  </div>

  <% end %>
  </div>

<% else %>
  <div class="container">
    <div class="message-body">You haven't added any games to your library yet. <%= link_to 'Add some', root_path, class: "goldbutton p-3" %></div>
  </div>
  <% end %>
</div>

app/views/library_game/index.html.erb
<h1>LibraryGame#index</h1>
<p>Find me in app/views/library_game/index.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron centering">
  <div class="content">
  <div class="search-font"><h1 class="title">Build Your Game Library</h1></div>

  <%= form_tag index_path, method: :get do %>

  <%= text_field_tag [:query],
  params[:query],
  class: "form-control input-lg home_search",
    id: "typed-text" %>

    <div class="input-group-btn ml-3">
      <%= submit_tag "Search", class: "btn goldbutton mt-3" %>
    </div>
  </div>
    <% end %>
  </div>
</div>

<h1 class="title">Recommended Titles</h1>

<div class="cards">
  <div class="wrapper">
    <div class="product-img">
  <img src="https://giantbomb1.cbsistatic.com/uploads/scale_medium/8/82063/2946176-smobox.jpg" class="cover">
    </div>
  <div class="product-info">
      <div class="product-text">
    <h1>Super Mario Odyssey</h1>
    <h2>NINTENDO SWITCH (2017)</h2>

    <p>Nintendo's favorite plumber and his new hat-shaped companion travel far beyond the Mushroom Kingdom in this Switch-exclusive 3D platformer.</p>
    </div>

    <div class="product-price-btn">
      <% if user_signed_in? %>
       <%= link_to '<button type="button">Add to library</button>'.html_safe, create_path(current_user, game_id: '56733'), method: :post %>
      <% else %>
      <%= link_to '<button type="button">Add to library</button>'.html_safe, new_user_session_path %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="wrapper">
    <div class="product-img">
  <img src="https://giantbomb1.cbsistatic.com/uploads/scale_medium/8/87790/1814649-box_ffttwotl.png" class="cover">
    </div>
  <div class="product-info">
      <div class="product-text">
    <h1>Final Fantasy Tactics: The War of the Lions</h1>
    <h2>PLAYSTATION PORTABLE (2007)</h2>

    <p>The game tells the story of a young hero, Ramza Beoulve, and his struggle to protect his beloved ones from the evil Lucavi. The story takes place around the War of the Lions, a conflict occurring due to the death of the King Ondorria, Lord of Ivalice.</p>
    </div>

    <div class="product-price-btn">
      <% if user_signed_in? %>
      <%= link_to '<button type="button">Add to library</button>'.html_safe, create_path(current_user, game_id: '27994'), method: :post %>
      <% else %>
      <%= link_to '<button type="button">Add to library</button>'.html_safe, new_user_session_path %>
      <% end %>
      </div>
    </div>
  </div>

<div class="wrapper">
    <div class="product-img">
  <img src="https://giantbomb1.cbsistatic.com/uploads/scale_medium/9/93770/2371208-genesis_megabomberman.jpg" class="cover">
    </div>
  <div class="product-info">
      <div class="product-text">
    <h1>Mega Bomberman</h1>
    <h2>GENESIS (1994)</h2>

    <p>Mega Bomberman is the name for the Sega Genesis release of the TurboGrafx-16 game, Bomberman '94, and is the third release in the Bomberman series.</p>
    </div>

    <div class="product-price-btn">
      <% if user_signed_in? %>
       <%= link_to '<button type="button">Add to library</button>'.html_safe, create_path(current_user, game_id: '18127'), method: :post %>
      <% else %>
      <%= link_to '<button type="button">Add to library</button>'.html_safe, new_user_session_path %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="wrapper">
    <div class="product-img">
  <img src="https://giantbomb1.cbsistatic.com/uploads/scale_medium/0/4938/609469-maniac_mansion_box_front_6570x8262.jpg" class="cover">
    </div>
  <div class="product-info">
      <div class="product-text">
    <h1>Maniac Mansion</h1>
    <h2>AMIGA (1987)</h2>

    <p>Maniac Mansion is a graphic adventure game originally released in 1987 by Lucasfilm Games. When the innocent Sandy is kidnapped by the maniacal Dr. Fred, it's up to her boyfriend Dave and his friends to her from certain death!</p>
    </div>

    <div class="product-price-btn">
      <% if user_signed_in? %>
       <%= link_to '<button type="button">Add to library</button>'.html_safe, create_path(current_user, game_id: '2037'), method: :post %>
       <% else %>
      <%= link_to '<button type="button">Add to library</button>'.html_safe, new_user_session_path %>
      <% end %>
      </div>
    </div>
  </div>

  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'gblogo.png' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Library", library_path(current_user, params[:id]), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag 'heartavatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user/show.html.erb
<%= User.find(params[:id]).username %>